[bitbucket_server]
bearer_token = "ATCTT3xFfGN0ht46jcd0DAlJpqFJbLEHaF9aw413xTZdLAotzdrDARu_3Qza4oj_Zy6u0AtvmaAE8F4Uun91Fhb3geDmRZfiEd3wKDpmXGm2GdyRA4TJaoDphKuhvgQy1UH26CUTLuLfAIcGQWxliGGUe7bldCMxT8rIeWUcX2WRrFaEBrk8bXc=7C2F7BA3"